name: End-to-end tests

on:
  push:

jobs:
  generate-matrix:
    runs-on: ubuntu-22.04
    outputs:
      specs: ${{ steps.set-matrix.outputs.specs }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Gerar lista de specs
        id: set-matrix
        run: |
          SPECS=$(find cypress/e2e -type f -name "*.cy.*" | jq -R . | jq -s '{include: map({spec: .})}')
          SPECS=$(echo "$SPECS" | jq -c .)
          echo "specs=$SPECS" >> $GITHUB_OUTPUT

  cypress-run:
    needs: generate-matrix
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      max-parallel: 3 # 👈 controla quantos jobs da matrix podem rodar ao mesmo tempo
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.specs) }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm ci

      - name: Executar Cypress (por spec)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npx cypress run --spec ${{ matrix.spec }}
        env:
          CYPRESS_VIDEO: true
          CYPRESS_SCREENSHOT_ON_RUN_FAILURE: true
