name: End-to-end tests
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Executar Cypress
        uses: cypress-io/github-action@v6
        with:
          record: true
          browser: chrome
        env:
          CYPRESS_VIDEO: true
          CYPRESS_SCREENSHOT_ON_RUN_FAILURE: true

      - name: Salvar screenshots e vídeos como artefatos
        if: failure() # Apenas se os testes falharem
        uses: actions/upload-artifact@v4 # Atualizado para v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos